### ISSUE TITLE
Any way to make this work for desktop version?

### ISSUE THREAD

**Issue by sananes** [cdes/figma-advanced-rename-plugin#2]
Hi, fantastic job on this!

First of all, is there any way I can have the tool show in desktop app? 
Also, anyway I can replace specific text, with something else?

**Comment by cdes** [comment]
@Sananes I'm working on creating a better way to install plugins on Desktop and Browser versions.  As of right now, the rename plugin does not allow you to find & replace, but Figma's rename feature does.

**Comment by cdes** [comment]
It's included now in http://figmaplus.com for browser and desktop.
